# Generated by Django 5.0.6 on 2025-09-30 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInfo',
            fields=[
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='drugs.drug')),
                ('administration', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
