# Generated by Django 5.0.6 on 2025-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_druginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drug',
            name='rxcui',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['drug_a', 'drug_b'], name='drugs_inter_drug_a__fe2996_idx'),
        ),
    ]
