# Generated by Django 5.0.6 on 2025-11-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drug_is_brand_drug_rxcui_alter_drug_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interaction',
            name='drugs_inter_drug_a__fe2996_idx',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='is_brand',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='rxcui',
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
