# Generated by Django 5.0.6 on 2025-11-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_drug_is_brand_drug_rxcui_alter_drug_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('generic_names', models.JSONField()),
                ('source_dataset', models.CharField(default='Kenya Kaggle', max_length=100)),
            ],
        ),
    ]
