# Generated by Django 5.0.6 on 2025-11-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_scanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginfo',
            name='auto_filled',
            field=models.BooleanField(default=False, help_text='Set True when content was auto-generated by the seeder'),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='drug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='druginfo', serialize=False, to='drugs.drug'),
        ),
    ]
