# Generated by Django 5.0.6 on 2025-11-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_profile_is_2fa_enabled_profile_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginfo',
            name='uses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
